### ISSUE TITLE
Changing game volume when sound is muted will unmute the sound but `game.sound.mute` stays `true`

### ISSUE THREAD

**Issue by 2called-chaos** [photonstorm/phaser-ce#31] opened 2017-02-16 16:04 UTC
**This Issue is about:** A bug in the API
**Reproduced with:** 2.6.2 and CE 2.7.3
**Description:** Changing game volume when sound is muted will unmute the sound but `game.sound.mute` stays `true`
**Sandbox example:** http://phaser.io/sandbox/edit/pwRPKVcR

I could understand that changing volume unmutes the game but it then should also revert mute to false.

My workaround currently:

```
({
  vc_updateVolume: function() {
    var nv, was_muted;
    nv = this.vc_getVolume();
    if (nv !== this.game.sound.volume) {
      was_muted = this.game.sound.mute;
      if (was_muted) { this.game.sound.mute = false }
      this.game.sound.volume = nv;
      if (was_muted) { this.game.sound.mute = true }
    }
  }
});

// ---
// generated by coffee-script 1.9.2
```

**Comment by samme** [comment] 2017-02-23 05:57
This may be unexpected but it seems to be the way the API is supposed to work.

**Comment by 2called-chaos** [comment] 2017-02-23 11:37
As I said I could understand that it unmutes when changing volume but leaving a broken state doesn't sound right to me. Took me a while to even figure it out because of the state of game.sound.mute still being true.

**Comment by samme** [comment] 2017-02-23 22:08
For reference: <http://codepen.io/samme/pen/dvyRzw>

**Comment by 2called-chaos** [comment] 2017-02-24 00:08
@samme Thanks for that.

I also just realized that

  * mute (silence)
  * change volume (from 1 to 0.5 - sound playing with 0.5 despite muted)
  * unmute (sound plays with 1 - volume got reset to what it was before mute)

**Comment by samme** [comment] 2017-02-24 15:57
> unmute (sound plays with 1 - volume got reset to what it was before mute)

Updated the example: the actual playback volume is

    (sound.volume = 1) * (game.sound.volume = 0.5)

so that part is normal.

**Comment by samme** [comment] 2017-04-01 19:39
Closing since this seems to be the intended behavior. Probably we should document it better.

**Closed by samme** 2017-04-01 19:39 UTC
Labels: not a bug
